-- premake5.lua
-- generated by muhhae

workspace "ImguiApp"
    configurations { "Debug", "Release" }

SRCDIR = "src" --Source Code Directory
BUILDDIR = "build" --Build Directory
OBJDIR = "%{BUILDDIR}/obj" --Obj Directory


project "ImguiApp"
    language "C++" --Languange

    buildoptions {"-std=c++23", "-Wall"} --CXXFLAGS
    linkoptions {"-lsfml-graphics -lsfml-window -lsfml-system"} --LDFLAGS
    links {"opengl32"}

    targetdir "%{BUILDDIR}/%{cfg.buildcfg}" 
    objdir "%{OBJDIR}/%{cfg.buildcfg}"

    includedirs {
        "include/**"
    }

    files {
        "%{SRCDIR}/**.h",
        "%{SRCDIR}/**.hpp", 
        "%{SRCDIR}/**.cpp",
        "include/**.cpp",
        "include/**.h"
    }

    filter "configurations:Debug"
        kind "ConsoleApp"
        defines { "DEBUG" }
        symbols "On"

    filter "configurations:Release"
        kind "WindowedApp"
        defines { "RELEASE" }
        optimize "On"